# Generated by Django 5.2 on 2026-08-29 12:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_geo_availability_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[accounts.models.validate_file_size]),
        ),
    ]
