# Generated by Django 5.2 on 2026-08-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_link_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='telegram_link_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
