# Generated by Django 5.2 on 2026-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_skills'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-rating'], name='profile_rating_idx'),
        ),
    ]
