"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file (never committed to git).
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No insecure fallback: a real key is required in every environment (local dev
# gets one from .env — see .env.example — so this only fires on a genuinely
# unconfigured checkout, instead of silently signing sessions/CSRF with a
# well-known committed-to-history default).
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Copy .env.example to .env and set a real "
        "secret key (see README.md), e.g.: "
        "python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False (safe) when unset; local dev opts into True explicitly via .env.
DEBUG = env_bool('DJANGO_DEBUG', False)
ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

if not DEBUG and (not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS):
    raise ImproperlyConfigured(
        "DJANGO_ALLOWED_HOSTS must list specific hosts when DJANGO_DEBUG=False "
        "(a wildcard '*' defeats Django's Host-header validation in production)."
    )

# Production-only hardening: these would break the plain-HTTP local dev server
# (forced HTTPS redirect, cookies marked Secure) so they only switch on once
# DEBUG=False, i.e. once a real deployment sets DJANGO_DEBUG accordingly.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_HTTPONLY = True
X_FRAME_OPTIONS = 'DENY'

# Behind a TLS-terminating reverse proxy (nginx/Caddy), Django only sees plain
# HTTP on the loopback hop, so request.is_secure() is False and SECURE_SSL_REDIRECT
# would loop forever. Opt in ONLY when the proxy is trusted to set (and to strip
# any client-supplied) X-Forwarded-Proto — see the nginx snippet in README.
if env_bool('DJANGO_BEHIND_TLS_PROXY', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Full origins (scheme://host[:port]) that may send unsafe (POST/PUT/…) requests.
# Django 4+ requires the production HTTPS origin(s) here for CSRF to pass; the
# CSRF cookie/Host check alone is not enough once served cross-scheme.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'django_filters',
    'crispy_forms',
    'crispy_bootstrap5',
    
    # Local apps
    'accounts.apps.AccountsConfig',  # 👈 только так!
    'myapp.apps.MyappConfig',        # 👈 только так!
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.maps_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'Gen_connect.sqlite3',
    }
}

# PostgreSQL for production — set DJANGO_DB_* and the engine switches over with
# no code change (psycopg must be installed). SQLite stays the default so a
# fresh checkout and the test suite need no database server.
if os.getenv('DJANGO_DB_NAME'):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DJANGO_DB_NAME'),
        'USER': os.getenv('DJANGO_DB_USER', ''),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', ''),
        'HOST': os.getenv('DJANGO_DB_HOST', 'localhost'),
        'PORT': os.getenv('DJANGO_DB_PORT', '5432'),
        'CONN_MAX_AGE': int(os.getenv('DJANGO_DB_CONN_MAX_AGE', '60')),
    }


# Cache — also the backing store for the login / password-reset / AI-assistant /
# Telegram-link rate limiters. The default LocMemCache is per-process, so those
# throttles only bite within a single worker: a multi-process (gunicorn) web
# deployment MUST set DJANGO_DB_CACHE=True (a shared, dependency-free DB cache —
# run `python manage.py createcachetable` once) or point CACHES at Redis/Memcached.
if env_bool('DJANGO_DB_CACHE', False):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': os.getenv('DJANGO_DB_CACHE_TABLE', 'gc_cache'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }


LOGIN_URL = 'login'
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SMTP_USER = os.getenv('SMTP_USER', '')
SMTP_PASSWORD = os.getenv('SMTP_PASSWORD', '')
SMTP_HOST = os.getenv('SMTP_HOST', 'smtp.gmail.com')
SMTP_PORT = int(os.getenv('SMTP_PORT', '587'))

# Fall back to the console backend when no SMTP credentials are configured,
# so development and demos work without a real mail server.
if SMTP_USER and SMTP_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = SMTP_HOST
EMAIL_PORT = SMTP_PORT
EMAIL_HOST_USER = SMTP_USER
EMAIL_HOST_PASSWORD = SMTP_PASSWORD
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = SMTP_USER or 'no-reply@generation-connect.local'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[
    BASE_DIR / 'static'
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.Users'

# Third-party integrations (all optional; features degrade gracefully if unset).
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
# The AI assistant talks to Groq's OpenAI-compatible API. Historically the Groq
# key was stored under GEMINI_API_KEY, so we accept either name.
GROQ_API_KEY = os.getenv('GROQ_API_KEY') or os.getenv('GEMINI_API_KEY', '')
GROQ_MODEL = os.getenv('GROQ_MODEL', 'llama-3.1-8b-instant')

OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
# Public @-handle of the bot, shown in the account-linking instructions so the
# user knows which chat to open. Not a secret; optional (the UI degrades to a
# generic "our bot" when unset).
TELEGRAM_BOT_USERNAME = os.getenv('TELEGRAM_BOT_USERNAME', '')

# Maps — a provider-agnostic layer lives in myapp/services/maps.py.
#   osm    (default) : free Leaflet tiles + OSRM routing + Nominatim geocoding, no key
#   mapbox / google  : drop-in, requires MAPS_API_KEY
MAPS_PROVIDER = os.getenv('MAPS_PROVIDER', 'osm').strip().lower()
MAPS_API_KEY = os.getenv('MAPS_API_KEY', '')
GEOCODING_TIMEOUT_SECONDS = 5
OSRM_BASE_URL = os.getenv('OSRM_BASE_URL', 'https://router.project-osrm.org').rstrip('/')
NOMINATIM_USER_AGENT = os.getenv('NOMINATIM_USER_AGENT', 'generation-connect-dev')

# Logging — without this the app's own logger.warning/error calls (the
# zero-recipient safety net in the overdue/stale/emergency sweeps, OSRM/Nominatim
# failures, Telegram send failures) propagate to the root logger, which has no
# handler under DEBUG=False and silently drops them. Route them to stderr so the
# process manager (systemd/journald, Docker) captures them.
LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': '[{asctime}] {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'standard'},
    },
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        # Server errors (500s) to stderr; 4xx (Not Found / Method Not Allowed,
        # logged at WARNING) stay quiet so they don't drown the signal.
        'django.request': {'handlers': ['console'], 'level': 'ERROR', 'propagate': False},
        'myapp': {'handlers': ['console'], 'level': LOG_LEVEL, 'propagate': False},
        'accounts': {'handlers': ['console'], 'level': LOG_LEVEL, 'propagate': False},
    },
}

LOGIN_REDIRECT_URL = 'profile'

