# Generated by Django 5.2 on 2026-05-13 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('region', models.CharField(choices=[('dushanbe', 'Душанбе'), ('sogd', 'Согд'), ('khatlon', 'Хатлон'), ('gbao', 'ГБАО'), ('rrp', 'РРП'), ('all', 'Все регионы')], default='all', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('region', models.CharField(choices=[('dushanbe', 'Душанбе'), ('sogd', 'Согд'), ('khatlon', 'Хатлон'), ('gbao', 'ГБАО'), ('rrp', 'РРП'), ('all', 'Все регионы')], default='all', max_length=100)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notifications_sent', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(limit_choices_to={'is_curator': True}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_type', models.CharField(choices=[('medical', 'Медицинская помощь'), ('grocery', 'Продукты и покупки'), ('transport', 'Транспорт'), ('household', 'Домашние дела'), ('emotional', 'Общение и поддержка'), ('documents', 'Документы'), ('other', 'Другое')], max_length=50)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('region', models.CharField(blank=True, choices=[('dushanbe', 'Душанбе'), ('sogd', 'Согд'), ('khatlon', 'Хатлон'), ('gbao', 'ГБАО'), ('rrp', 'РРП')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Свободный'), ('active', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('alarm_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, limit_choices_to={'is_volunteer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос помощи',
                'verbose_name_plural': 'Запросы помощи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='reports/')),
                ('region', models.CharField(blank=True, choices=[('dushanbe', 'Душанбе'), ('sogd', 'Согд'), ('khatlon', 'Хатлон'), ('gbao', 'ГБАО'), ('rrp', 'РРП')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_reports', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_reports', to='myapp.event')),
                ('help_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_reports', to='myapp.helprequest')),
            ],
            options={
                'verbose_name': 'Фотоотчет',
                'verbose_name_plural': 'Фотоотчеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
