# Generated by Django 5.2 on 2026-08-25 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, choices=[('dushanbe', 'Душанбе'), ('sogd', 'Согд'), ('khatlon', 'Хатлон'), ('gbao', 'ГБАО'), ('rrp', 'РРП')], max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_volunteer_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка волонтера',
                'verbose_name_plural': 'Заявки волонтеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
