# Generated by Django 5.2 on 2026-08-29 12:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_geo_availability_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoreport',
            name='image',
            field=models.ImageField(upload_to='reports/', validators=[accounts.models.validate_file_size]),
        ),
    ]
