# Generated by Django 5.2 on 2026-08-31 10:04

from django.db import migrations, models


def urgent_to_high_priority(apps, schema_editor):
    """Carry the legacy is_urgent boolean forward onto the new graded field."""
    HelpRequest = apps.get_model('myapp', 'HelpRequest')
    HelpRequest.objects.filter(is_urgent=True).update(priority='high')


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_photoreport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='priority',
            field=models.CharField(choices=[('normal', 'Обычный'), ('high', 'Высокий'), ('emergency', 'Экстренный')], db_index=True, default='normal', max_length=20),
        ),
        migrations.RunPython(urgent_to_high_priority, migrations.RunPython.noop),
    ]
