# Generated by Django 5.2 on 2026-08-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_helprequest_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='work_stage',
            field=models.CharField(choices=[('assigned', 'Назначен'), ('en_route', 'В пути'), ('arrived', 'На месте'), ('in_progress', 'Выполняется')], default='assigned', max_length=20),
        ),
    ]
