# Generated by Django 5.2 on 2026-09-02 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_helprequest_work_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('acknowledged', 'Принят'), ('resolved', 'Решён'), ('cancelled', 'Отменён')], db_index=True, default='open', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, choices=[('dushanbe', 'Душанбе'), ('sogd', 'Согд'), ('khatlon', 'Хатлон'), ('gbao', 'ГБАО'), ('rrp', 'РРП')], max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies_cancelled', to=settings.AUTH_USER_MODEL)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_reports', to='myapp.helprequest')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies_resolved', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(limit_choices_to={'is_volunteer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сигнал опасности',
                'verbose_name_plural': 'Сигналы опасности',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='myapp_emerg_status_598f1f_idx')],
            },
        ),
    ]
