# Generated by Django 5.2 on 2026-09-02 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_emergencyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emergencyreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('open', 'acknowledged'))), fields=('help_request', 'volunteer'), name='uniq_active_emergency_per_volunteer_task'),
        ),
    ]
