# Generated by Django 5.2 on 2026-09-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_emergencyreport_uniq_active_emergency_per_volunteer_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='stale_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
