# Generated by Django 5.2 on 2026-09-04 05:45

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_product_donation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('lost', 'Потерян'), ('found', 'Найден')], db_index=True, max_length=10)),
                ('pet_name', models.CharField(blank=True, max_length=120)),
                ('species', models.CharField(choices=[('dog', 'Собака'), ('cat', 'Кошка'), ('bird', 'Птица'), ('other', 'Другое')], default='other', max_length=20)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('region', models.CharField(blank=True, choices=[('dushanbe', 'Душанбе'), ('sogd', 'Согд'), ('khatlon', 'Хатлон'), ('gbao', 'ГБАО'), ('rrp', 'РРП')], max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='pets/', validators=[accounts.models.validate_file_size])),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('matched', 'Есть совпадение'), ('resolved', 'Воссоединён'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pet_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление о животном',
                'verbose_name_plural': 'Объявления о животных',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'report_type', '-created_at'], name='myapp_petre_status_4297cc_idx')],
            },
        ),
    ]
