# Generated by Django 5.2 on 2026-09-30 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_inkind_donations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['status', '-created_at'], name='helpreq_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['region', 'status'], name='helpreq_region_status_idx'),
        ),
        migrations.AddIndex(
            model_name='photoreport',
            index=models.Index(fields=['-created_at'], name='photoreport_created_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteerapplication',
            index=models.Index(fields=['status', '-created_at'], name='volapp_status_created_idx'),
        ),
    ]
