# Generated by Django 5.2 on 2026-10-01 07:36

import myapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_event_event_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='phone',
            field=models.CharField(max_length=30, validators=[myapp.validators.validate_tj_phone]),
        ),
        migrations.AlterField(
            model_name='petreport',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, validators=[myapp.validators.validate_tj_phone]),
        ),
    ]
